#!/usr/bin/env expect

set user [lindex $argv 0 ]

## login relay
spawn ssh ${user}@relay01.baidu.com

interact -o -nobuffer "$" return

## ssh server
#send "ssh $user@$server\n"
#send "clear \n"

interact
